### ISSUE TITLE
Panic on start when using actix 0.12.0

### ISSUE THREAD

**Issue by vcfxb** [rcos/Telescope#125]
Error message: 
```
[2021-06-16T17:26:44Z INFO  telescope] Server timezone: -04:00
thread 'main' panicked at '`spawn_local` called from outside of a `task::LocalSet`', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.0/src/task/local.rs:303:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-06-16T17:26:44Z INFO  telescope::web::csrf] CSRF Janitor Started
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.0/src/runtime/context.rs:37:26
stack backtrace:
   0:     0x55a359989e10 - std::backtrace_rs::backtrace::libunwind::trace::h25e12e0d899beba0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55a359989e10 - std::backtrace_rs::backtrace::trace_unsynchronized::h70e61195d6ae3df6
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a359989e10 - std::sys_common::backtrace::_print_fmt::hba93ab80d779695a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55a359989e10 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf092b5883b4b2e50
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55a3599abbcc - core::fmt::write::hf68bc350a8f2f0dc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
   5:     0x55a359981f22 - std::io::Write::write_fmt::hf66811b1bc767436
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
   6:     0x55a35998bfc5 - std::sys_common::backtrace::_print::hd425a11bfe1f20f8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55a35998bfc5 - std::sys_common::backtrace::print::h6d678795c1e61e13
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55a35998bfc5 - std::panicking::default_hook::{{closure}}::h78a02a4a0dee5e7e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
   9:     0x55a35998bb1a - std::panicking::default_hook::h56eb7eda02f355a7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
  10:     0x55a35998c761 - std::panicking::rust_panic_with_hook::hb27ea14285131c61
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
  11:     0x55a35998c2a7 - std::panicking::begin_panic_handler::{{closure}}::hc552fcee62aad17f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
  12:     0x55a35998a2cc - std::sys_common::backtrace::__rust_end_short_backtrace::hb9f0aa9a78e885a0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55a35998c209 - rust_begin_unwind
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
  14:     0x55a3599a9b21 - core::panicking::panic_fmt::h12ac4570ea43d06f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
  15:     0x55a3599a98b3 - core::option::expect_failed::h7e0f81ae38d4dc42
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1260:5
  16:     0x55a3596c3ee7 - tokio::runtime::context::time_handle::h70eef2f25eddd92c
  17:     0x55a3596c68c4 - tokio::time::driver::sleep::sleep::hb0af6351f62cda98
  18:     0x55a3590b46aa - actix::actor::AsyncContext::run_interval::h9ef049621bcde2a3
  19:     0x55a3591fc239 - <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll::h877af50666482731
  20:     0x55a3591f7987 - <actix::contextimpl::ContextFut<A,C> as core::ops::drop::Drop>::drop::h456a5ac9d666d2f0
  21:     0x55a35901e5bd - core::ptr::drop_in_place::h707fecb5e11580fc
  22:     0x55a3590261b9 - tokio::macros::scoped_tls::ScopedKey<T>::with::h7663601c494a21cb
  23:     0x55a359217353 - actix::actor::Actor::start::h689a4ca9361a5ab8
  24:     0x55a35914a1c4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4c1a0c74fdeeb55b
  25:     0x55a3591f7b39 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::h3c020c53c694f397
  26:     0x55a359187222 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf98e13f161c64edc
  27:     0x55a3591f4982 - tokio::macros::scoped_tls::ScopedKey<T>::set::h555e0f7314fb0755
  28:     0x55a359218c2d - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h8f13a8017e0689b3
  29:     0x55a3590b737f - tokio::runtime::context::enter::h20a7b86402c98586
  30:     0x55a35902730d - tokio::runtime::handle::Handle::enter::hbfa66986d5bce10e
  31:     0x55a359056d17 - telescope::main::ha8dcdac39c413e10
  32:     0x55a359079ba3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfa62b5d09d369039
  33:     0x55a35909eb89 - std::rt::lang_start::{{closure}}::hf38831fdb195bc6b
  34:     0x55a35998cc77 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h78040f802d89ccdc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:259:13
  35:     0x55a35998cc77 - std::panicking::try::do_call::h6853cad536dd09a1
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
  36:     0x55a35998cc77 - std::panicking::try::h827495f03a9fbb9a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
  37:     0x55a35998cc77 - std::panic::catch_unwind::h4bdf17571090eb17
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
  38:     0x55a35998cc77 - std::rt::lang_start_internal::h2f319c33bb013f29
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:51:25
  39:     0x55a359056dc2 - main
  40:     0x7fed84b0f09b - __libc_start_main
  41:     0x55a358f7412a - _start
  42:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction (core dumped)
```

Current solution is to stay on actix 0.10.0 until whatever underlying tokio version mismatch is fixed.

**Comment by Alfriadox** [comment]
After some research, this appears it will be solved on the release of actix-web 4.0 (see https://github.com/actix/actix-web/pull/1813)
